### ISSUE TITLE
Automatic choice for imfilter() vs. imfilter_fft() based on kernel size

### ISSUE THREAD

**Issue by juliohm** [timholy/Images.jl#222]
Hi Tim,

Is there any way to know beforehand which will be faster given the kernel size? Consider the following example:

```julia
Pkg.add("ImageQuilting")
using ImageQuilting
ImageQuilting.example()
```

We can see that the case with green apples is noticeably slower even though the kernel size is in the same range of the other cases. I'm wondering if we can choose between `imfilter()` and `imfilter_fft()` automatically.

**Comment by juliohm** [comment]
Just for curiosity, can you run this code to see if you get similar performance behavior?

```julia
using Images
using PyPlot

img = zeros(1000,1000)

wrange = 3:100

times1 = []
times2 = []
for s in wrange
  t1 = @elapsed imfilter(img, zeros(s,s))
  t2 = @elapsed imfilter_fft(img, zeros(s,s))
  push!(times1, t1)
  push!(times2, t2)
end

figure()
plot(wrange, times1, label="imfilter")
plot(wrange, times2, label="imfilter_fft")
legend()
```

This is what I get on my Dell XPS 13:

![test](https://cloud.githubusercontent.com/assets/3345261/17127001/d5f8a1ce-52c7-11e6-9296-ff5023741cef.png)

The switch point is around 40 pixels.

**Comment by mronian** [comment]
If it helps, here's the output on my machine :)

![figure_1](https://cloud.githubusercontent.com/assets/6151667/17127339/79adabf2-5322-11e6-9cde-89ffed3c2609.png)

**Comment by timholy** [comment]
One can observe several interesting things in these graphs:
- The first point is corrupted by JIT compilation (better to run once before you enter your timing loop)
- You should be puzzled about why the curve for `imfilter` is *linear* in `s`; you would naively expect it to be *quadratic* in `s`.

The linear behavior arises because Images includes a clever optimization: before doing anything, it tests whether your kernel is approximately [separable](http://blogs.mathworks.com/steve/2006/10/04/separable-convolution/). I predict that if you use `rand` for your kernel rather than `zeros` you'll see a very different result.

Right now the check for separability is buried inside [this method](https://github.com/timholy/Images.jl/blob/4f0fc15609533c29d574f892a64ff88ecec5cb28/src/algorithms.jl#L640-L663), but if you're thinking about automatically choosing one or the other method then I'd recommend splitting the separability-check into a standalone function.

**Comment by juliohm** [comment]
That is awesome Tim, I will keep that in mind. Do you know why @mronian plot for the fft version oscilates much more than mine?

**Comment by timholy** [comment]
This is almost done in ImagesFiltering (I just need to replace [this line](https://github.com/JuliaImages/ImagesFiltering.jl/blob/b978eac69fc010198c76a64aee5fd281f490553d/src/ImagesFiltering.jl#L448) with something smarter), so to prevent someone from wasting their time I'll close this now.
