### ISSUE TITLE
Float32 to Ufixed16 conversion fails when creating an image

### ISSUE THREAD

**Issue by ikirill** [timholy/Images.jl#256]
I have a Float32 matrix

    (typeof(result_scaled),size(result_scaled)) = (Array{Float32,2},(512,512))

and trying to convert it to a 16-bit greyscale image like this:

    umin, umax = quantile(vec(result_array), [0.025, 0.975])
    result_scaled = (result_array - umin) / (umax - umin)
    image = Image{RGB{Ufixed16}}(result_scaled)

fails with a very uninformative error message. If I make an image from result_array instead of result_scaled, everything works fine, same if I clamp result_scaled using `min(0.f0, max(1.f0, result_scaled))`, it works too. Note that Images doesn't seem to care if a Float32 input is out of [0,1], so I didn't expect it to fail with Ufixed16.

    ERROR: InexactError()
     in trunc at float.jl:345
     in copy! at abstractarray.jl:174
     in convert at array.jl:233
     in _convert at /***/.julia/v0.4/Images/src/core.jl:277
     in go2 at /***.jl:190

    julia> versioninfo()
    Julia Version 0.4.0-dev+2876
    Commit f164ac1 (2015-01-22 22:58 UTC)
    Platform Info:
      System: Linux (x86_64-linux-gnu)
      CPU: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

**Comment by lucasb-eyer** [comment]
The `Ufixed16` type can't hold numbers outside the range [0,1]: `Ufixed16(1.1)` will `InexactError`-out. What result would you have expected for those pixels outside of your quantiles?

**Comment by ikirill** [comment]
I would expect them to be clamped to [0,1]. IIUC that's just what happens if I use ordinary floating point values: there is no error if I make an image consisting of all `2.0`s, and also no error when writing it to a file (which ends up bit 8 bit greyscale, so I think clamping is implicit there).

I'm sure Ufixed16's behaviour is reasonable in some sense, but for images, the default behaviour seems to be to clamp things implicitly.

**Comment by timholy** [comment]
You get the same error from `convert(UInt, -2)`. In both cases, it's because the number you're supplying as an input simply can't be represented as the type you're asking for.

So there are several options:
- Change julia's behavior for `convert(UInt, -2)`. I predict a tough sell on that.
- Make `FixedPointNumbers` (which is where the behavior you're concerned about comes from) act differently than the rest of julia. Also seems unlikely to fly.
- Make Images first clamp each value before calling `convert` on it. The downside is it will massively slow down conversions for anyone who doesn't need to clamp (branches are slow---it's a CPU thing, not a julia thing).
- Make the user clamp first in cases where it's necessary

Currently we do the last one. Care to lobby for something different?

**Comment by ikirill** [comment]
> Make Images first clamp each value before calling convert on it. The downside is it will massively slow down conversions for anyone who doesn't need to clamp (branches are slow---it's a CPU thing, not a julia thing).

SSE has the `minss` and `maxss` instructions, which don't involve branching.

    julia> function f(x::Float32); max(0.f0, min(1.f0, x)); end
    julia> @code_native f(0.4f0)
            .section        __TEXT,__text,regular,pure_instructions
    Filename: none
    Source line: 1
            push    RBP
            mov     RBP, RSP
            movabs  RAX, 4485725264
    Source line: 1
            minss   XMM0, DWORD PTR [RAX]
            xorps   XMM1, XMM1
            maxss   XMM0, XMM1
            pop     RBP
            ret

This doesn't seem to work with vectors, though:

    julia> function f(x::Vector{Float32}); max(0.f0, min(1.f0, x)); end
    julia> code_native(f, (Vector{Float32},))
            .section        __TEXT,__text,regular,pure_instructions
    Filename: none
    Source line: 1
            push    RBP
            mov     RBP, RSP
            push    RBX
            sub     RSP, 24
            mov     QWORD PTR [RBP - 32], 2
    Source line: 1
            movabs  RBX, 4471573408
            mov     RAX, QWORD PTR [RBX]
            mov     QWORD PTR [RBP - 24], RAX
            lea     RAX, QWORD PTR [RBP - 32]
            mov     QWORD PTR [RBX], RAX
            mov     QWORD PTR [RBP - 16], 0
            mov     RDI, QWORD PTR [RSI]
            movabs  RAX, 4485730864
            movss   XMM0, DWORD PTR [RAX]
    Source line: 1
            movabs  RAX, 4498041712
            call    RAX
            movabs  RCX, 4498041728
            mov     QWORD PTR [RBP - 16], RAX
            xorps   XMM0, XMM0
            mov     RDI, RAX
            call    RCX
            mov     RCX, QWORD PTR [RBP - 24]
            mov     QWORD PTR [RBX], RCX
            add     RSP, 24
            pop     RBX
            pop     RBP
            ret

Writing element-by-element maybe works (it does use `{min,max}ss`), but I cannot tell

    julia> function f2(x::Vector{Float32}); y = copy(x); @inbounds for i=1:length(y); y[i] = max(0.f0, min(1.f0, y[i])); end; end
    julia> code_native(f2, (Vector{Float32},))
    <snip 2.5 screens of assembly>

It also doesn't use SIMD instructcions `{min,max}ps`, I don't really know what to expect.

> Currently we do the last one. Care to lobby for something different?

It's inconsistent with how Images behaves for other floating-point numbers, like Float32. A `Float32` color value `-1.f0` is still invalid, but Images accepts the invalid color, and silently clamps it to [0,1].

Also, the clamping only needs to be done when conversion happens between possibly-incompatible formats like `Float32 -> Ufixed16`. Clamping `Float32 -> Float32` would be wrong, I think.

I have to say I don't feel very strongly about this one way or the other, I just found the behaviour unexpected.

**Comment by timholy** [comment]
Put `@simd` after your `@inbounds` and you'll get it to vectorize. Maybe not as bad as I thought.

> A Float32 color value -1.f0 is still invalid, but Images accepts the invalid color, and silently clamps it to [0,1].

The key point is that the allowable range of any value is determined by the element type, not the colorspace. Imposing bounds on the colorspace seems impossible, given the nonlinear "boundaries" of many spaces. From that perspective, I think there is never an inconsistency (but please do point it out if I'm wrong).

I'm not exactly sure what you mean by "silently clamps," because Images does very little clamping. For example, if you gaussian-filter an image that has out-of-bounds values for an RGB, it will use the out-of-bounds values. The only two usages of `clamp` that I can find are (1) when converting between colorspaces like YCbCr and RGB, and (2) with `getindex` from an `Overlay`. Perhaps those (especially the first) are indeed inconsistent, and an error should be thrown. Is that the inconsistency you're concerned about?

**Comment by ikirill** [comment]
> I'm not exactly sure what you mean by "silently clamps,"

If I make a Float32 image of 0, +1, -1, +2, then save it, the -1's and +2's get lost, converted to 0 and 1. So while there is no clamping in Image itself, the clamping is implicit in how it interprets Float32 values as colors when necessary. There is also no error (InexactError, or anything) when it does this.

> Is that the inconsistency you're concerned about?

No. I find it inconsistent that passing invalid Float32 colors to an image that uses Ufixed16 causes an error, instead of clamping the invalid values, while passing invalid Float32 colors to an image that uses Float32 causes no error, and the invalid colors get clamped when the image is saved.

> Put @simd after your @inbounds and you'll get it to vectorize.

I don't think this works, there's a bunch of stuff in the output that I don't understand, but the relevant bit of assembly output is this:

    Source line: 1
            mov     RAX, QWORD PTR [RAX + 8]
            movabs  RDX, 4631260368
            movss   XMM0, DWORD PTR [RDX]
            xorps   XMM1, XMM1
            movss   XMM2, DWORD PTR [RAX]
            minss   XMM2, XMM0
            maxss   XMM2, XMM1
            movss   DWORD PTR [RAX], XMM2

What I would to see here is instructions minps/maxps that operate on packed vectors of 4 floats, which is the really efficient thing to do.

**Comment by timholy** [comment]
Ah, "and then save it" was the key phrase that was missing from this conversation---I had no clue what you were concerned about. Yes, you're absolutely right. The code in question is [here](https://github.com/timholy/Images.jl/blob/e40e11c3569d5ca0de623a076e856cb5953a4cab/src/io.jl#L338-L355). Yes, perhaps clamping before saving is dangerous and we should change it to `MapNone` so it throws an error. Or at least issue a warning. One caveat is that we don't want a warning if the user [supplied her own `mapinfo`](https://github.com/timholy/Images.jl/blob/e40e11c3569d5ca0de623a076e856cb5953a4cab/src/io.jl#L297) to perform on-the-fly clamping. (That's a better approach than `imwrite(clamp(img), filename)` because you don't have to allocate a temporary object.) Maybe we need a `ClampWarn` type specifically for this use-case---it could hold a boolean flag, and `imwrite` could (1) first clear the flag, (2) write the image, and (3) check the status of the flag after writing is done and issue a warning if it's `true`. 

In support of your notion of inconsistency, while looking into this issue I noted we currently have #257.

To me display code is a completely different matter---it's not a transformation that alters the underlying data representation, so clamping for display purposes (i.e., ImageView) seems totally fine to me. However, I'm happy to entertain arguments to the contrary.

**Comment by timholy** [comment]
Oh, and re `@simd`: I tend to look at `@code_llvm`, which suggests there is vectorization.

**Comment by timholy** [comment]
OK, fixed.
