### ISSUE TITLE
Stackoverflow when converting an RGBA image to Gray-scale image

### ISSUE THREAD

**Issue by r9y9** [timholy/Images.jl#382]
I have a stack overflow problem when converting an RGBA image to gray-scale image on Julia v0.4.0-rc4, while converting an RGB image to gray-scale image works as expected.

```julia
julia> using Images

julia> img = imread("data/lenna.png")
RGBA Images.Image with:
  data: 256x256 Array{ColorTypes.RGBA{FixedPointNumbers.UfixedBase{UInt8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> gray_img = convert(Image{ColorTypes.Gray}, img)
ERROR: StackOverflowError:
 in _convert at /Users/user1/.julia/v0.4/Colors/src/conversions.jl:49 (repeats 80000 times)
```

I'm not sure if this is a problem in Images.jl or Colors.jl. Please see my notebook at http://nbviewer.ipython.org/gist/r9y9/c50c72e201755f416bee for more detailed steps.

**Comment by SimonDanisch** [comment]
That's because the conversion doesn't seem to be defined.
Not a big surprise, since it's not really clear what should happen to the alpha channel with that conversion. Maybe strip the alpha channel off first, or convert to `GrayA`?
Both seem to work fine for me.
But producing a stackoverflow instead of a reasonable error message is not good eitherway!

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaGraphics/Colors.jl/pull/240
