### ISSUE TITLE
Line 1272/1274, algorithms.jl gives type of Array{Any} leading to garbage Image while saving

### ISSUE THREAD

**Issue by mronian** [timholy/Images.jl#503]
Need to use ```convert(Array{Colors.base_colorant_type(eltype(img)){dtype}}, img)```

**Comment by mronian** [comment]
Same in Line 1319.

**Comment by mronian** [comment]
@timholy This seems to be occurring in many places. Wherever I am using [convert(type) for x in img] it creates an array of type ```Any``` instead of ```type```. Is this meant to happen or is this a bug?

**Comment by mronian** [comment]
Again, it occurs in line 1321. Doesnt occur in Line 1302 though.

**Comment by timholy** [comment]
This is the thing I mentioned about "type instability" due to your use of a `dtype` string to encode type information. Julia needs to know the type of a comprehension in order to allocate the correct type.

If you don't mind, I'll just rewrite that code to illustrate how to solve this problem; you can then follow that pattern in future work. OK? I'll post it as a PR and you can comment on it and make me make it better, just like I do for yours :stuck_out_tongue: .

Also a nice github trick: click on the source file you want to refer to, press the 'y' key on your keyboard, then select the line(s) you want to describe, then copy the URL up in the location bar of your browser. Then paste in the lines [like this](https://github.com/timholy/Images.jl/blob/06eca29a0cf2b18e141e000f5a992f2a4c64b566/src/algorithms.jl#L1274). (You can see what I did by clicking on the "pencil" icon for this comment, it will show you the raw ASCII.)

The reason for hitting 'y' is that it will include the commit SHA in the URL, and thus is a "permalink" to that particular line. If you don't do that, it will always refer to whatever is the current master, and that's very likely to get out of sync.

**Comment by timholy** [comment]
Oh, wait, I see that #505 seems like the right way to fix it, so let's go with that.

**Comment by timholy** [comment]
> @timholy This seems to be occurring in many places. Wherever I am using [convert(type) for x in img] it creates an array of type Any instead of type. Is this meant to happen or is this a bug?

It's type-instability. Use `@code_warntype` on your functions and look for red. Once you eliminate the red, then you won't have that problem anymore.
