### ISSUE TITLE
save() for a 16bit Image does not preserve the 16 bit property. 

### ISSUE THREAD

**Issue by mronian** [timholy/Images.jl#504]
```julia
julia> img
Gray Images.Image with:
  data: 256×256 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> save("test.jpg", img)

julia> load("./test.jpg")
Gray Images.Image with:
  data: 256×256 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    colorspace: Gray
    spatialorder:  x y

```

**Comment by timholy** [comment]
http://blogs.adobe.com/jkost/2010/07/saving_16_bit_images_as_jpeg.html. Use PNG if you want 16-bit.

For future reference, Images.jl doesn't do any IO itself; any load/save issues might be better filed with the relevant package (e.g., ImageMagick.jl, QuartImageIO.jl, or whatever it is that's doing the saving), simply because any PR that closes that issue will be against the relevant package.

**Comment by mronian** [comment]
Ok :)
