### ISSUE TITLE
What is the best way to determine Image type?

### ISSUE THREAD

**Issue by loganwilliams** [timholy/Images.jl#506]
After loading an image, what is the best way to determine its type? Ideally, I'd like a one liner that tells me if it is grayscale or anything with multiple channels. Currently, I'm using `if typeof(im.data[1]) <: Gray`, but that seems a bit hacky. Likewise, I could do a string comparison on `colorspace(im)` but comparing strings instead of types also seems not ideal.

**Comment by timholy** [comment]
Yes, the strings-based processing is a legacy of long ago. It will be revamped some time in the future.

`eltype` is much better than `typeof(im.data[1])`, because it works for any `AbstractArray` (even if it's empty). You could define
```jl
isgray(img) = false
isgray{T<:Gray}(img::AbstractArray{T}) = true
```
and 
```jl
isrgb(img) = false
isrgb{T<:AbstractRGB}(img::AbstractArray{T}) = true
```

But finally, perhaps the best thing is not to push such tests inside an `if` statement at all: you can dispatch to different methods, just as illustrated here for `isgray` and `isrgb`. That's the most julian way.

**Comment by loganwilliams** [comment]
Great, thanks for the tip. I hadn't thought about using multiple dispatch in that way, but that's pretty cool.
